### ISSUE TITLE
pinned-only does not save properly, it always gets set to true after opening the options page

### ISSUE THREAD

**Issue by meadowsjared** [timtrinidad/chrome-extension-force-new-tabs-to-main-window#1]
`pinned-only` does not save properly, it always gets set to true after opening the options page

I've fixed this in my local repo, if you'll allow me to submit a PR to fix it @timtrinidad

**Comment by timtrinidad** [comment]
Good catch - thanks! This repo should allow PRs - is it not allowing you?

**Comment by meadowsjared** [comment]
Tim,

Thank you for getting back to me sir!

Ya I'm sorry, I tried to submit a PR already but it's throwing this error:
[image: image.png]
I believe you need to add me here:
https://github.com/timtrinidad/chrome-extension-force-new-tabs-to-main-window/settings/access
to allow me to submit a PR for your review.

I do web development work for my main job (I've been doing it for about 20
years or so) so I'm happy to help out.  I find your extension invaluable as
I use addon's for games that I play which open stat tabs, but it's VERY
annoying because it will often open it over the top of a video I'm watching
on my 2nd monitor (if that was the last tab I interacted with).

In addition to helping you solve those two issues I've found, I was hoping
to submit a third PR to add a feature where you can both toggle which
window is main just by clicking the icon, as well as adding a "highlighted
icon" to that window, to make it very simple for the user to understand
which window is currently set to being the main window.  I already have
this working, but I still need to get the icon stuff working, I'll try and
get to that in the next couple of days maybe.

Please let me know if you have any questions, thanks again for getting back
to me!

-Jared Meadows

**Comment by timtrinidad** [comment]
The image didn't come through. Are you not able to create a fork, make your changes there, and then open up a PR from your fork to this repo?

**Comment by meadowsjared** [comment]
I could create a fork, but if I did that, that would only create a separate repo and when I submit my PR, it would go to my won repo, which would defeat the purpose of me trying to help yours, rather than publishing it myself and creating yet another chrome web store entry (which feels spammy).  Here is the text from the image:

when I ran this command:
git push --set-upstream origin current-window-main-menu
```
ERROR: Permission to timtrinidad/chrome-extension-force-new-tabs-to-main-window.git denied to meadowsjared.
fatal: Could not read from remote registry.

Please make sure you have correct access rights
and the repository exists.

```

**Comment by timtrinidad** [comment]
Creating a fork and opening a pull request from that fork [is standard practice](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) for contributions to open source projects. This allows anyone to propose changes to OSS without being added as a collaborator.

Here's an example - this is a PR into the `kubernetes` repository from a user-cloned fork: https://github.com/kubernetes/kubernetes/pull/107658

**Comment by jaredmeadowsLB** [comment]
ah ok, sorry about that, I'll do that then, I'm accustomed to just being added as we've been doing that at work for years, I'll give that a shot though!

**Comment by meadowsjared** [comment]
ah ok, sorry about that, I'll do that then, I'm accustomed to just being added to the repo as we've been doing that at work for years, I'll give that a shot though!

**Comment by meadowsjared** [comment]
ok please let me know if you have any issues with the PR
